In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [9]:
(2 ** np.arange(1, 21)) / np.arange(1, 21)

array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04,   5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [14]:
sum((0.1 ** (3* np.arange(6))) * 0.2 ** (4*np.arange(6)))

1.00000160000256

In [15]:
sum( np.vectorize(lambda x: (0.1**(3*x)) * 0.2**(4*x) )(np.arange(6)) )

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [2]:
a = np.ones((8,8))
a[1::2,::2] = 0
a[::2,1::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [40]:
X = np.random.random((5, 2))

R = [np.sqrt(X[:, 0] ** 2, X[:, 1] ** 2), np.arctan2(X[:, 1], X[:, 0])]
R

[array([ 0.62012883,  0.85687996,  0.50334773,  0.90014478,  0.74977109]),
 array([ 0.79452704,  0.25411102,  0.90584283,  0.67789694,  0.82329599])]

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [45]:
X = np.random.random((10, 10))

np.unravel_index(np.argmax(X, axis=None), X.shape)

(4, 3)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [55]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

t = X - y
r = np.sqrt(t[:,0]**2 + t[:,1] ** 2)
print(X[np.argmax(r)])

[ 0.88887368  0.41300376]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [62]:
N = 100
x = np.linspace(-3, 3, N)
fx = np.vectorize(lambda x: x**2 +2*x + 6 if x<0 else ( x+6 if x<=2 else x**2 +4*x-4))(x)

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [70]:
X = np.random.random((10, 10))

X = X - np.mean(X, axis = 0)
X.mean(axis = 0)

array([ -5.55111512e-17,  -3.33066907e-17,  -3.33066907e-17,
        -1.11022302e-17,   7.77156117e-17,   6.66133815e-17,
         6.10622664e-17,  -8.88178420e-17,   4.44089210e-17,
         3.33066907e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [71]:
X = np.random.normal(loc=5, scale=2., size=1000)

E = np.mean(X)
D = np.var(X)
print(E, D)

5.0261087689 4.07865531145


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [26]:
n = 5
d = np.arange(n)
np.stack([np.roll(d, i) for i in range(n, 0, -1)])

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])